FROM docker.elastic.co/kibana/kibana:6.8.0
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.2.0/enhanced-table-1.2.0_6.8.0.zip
RUN /usr/share/kibana/bin/kibana --optimize